{% set name = "lightcurvelynx" %}
{% set version = "0.1.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightcurvelynx-{{ version }}.tar.gz
  sha256: 25f9e9b18aeb9578303ac443a2ca2bbdc270c7cff9bd4cfdbf713a2d0ae7357e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - cdshealpix
    - citation-compass >=0.0.3
    - matplotlib-base
    - mocpy
    - nested-pandas
    - numpy >=2
    - pandas
    - pooch
    - PyYAML >=6
    - regions
    - scipy
    - tqdm

test:
  imports:
    - lightcurvelynx
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/lincc-frameworks/lightcurvelynx
  summary: 'A Fast and Nimble Package for Time Domain Astronomy'
  description: |
    LightCurveLynx aims to provide a flexible, scalable, and user-friendly time-domain
    simulation software with realistic effects and survey strategies. The software
    package consists of multiple stages: a flexible framework for consistently
    sampling model parameters, realistic models of time varying phenomena (such as
    supernovae and AGNs), effect models (such as dust extinction), and survey
    characteristics (such as cadence, filters, and noise).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremykubica
    - hombit
    - mi-dai
    - olivialynn
