{% set name = "lightcurvelynx" %}
{% set version = "0.6.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/37/a5/347fdfbc32e928460ef77eb9dea1e8bd4034a6e658e61513363b19c1e0fc/lightcurvelynx-{{ version }}.tar.gz
  sha256: 06c9b946291b350c8ce589fde72864c764b3e143d6182681ab0b8b3d5c9f86e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - astroquery
    - cdshealpix
    - citation-compass >=0.0.3
    - matplotlib-base
    - mocpy
    - nested-pandas >=0.6
    - networkx
    - numpy >=2
    - pandas
    - pooch
    - PyYAML >=6
    - regions
    - scipy
    - sncosmo
    - tqdm

test:
  imports:
    - lightcurvelynx
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/lincc-frameworks/lightcurvelynx
  summary: 'A Fast and Nimble Package for Time Domain Astronomy'
  description: |
    LightCurveLynx aims to provide a flexible, scalable, and user-friendly time-domain
    simulation software with realistic effects and survey strategies. The software
    package consists of multiple stages: a flexible framework for consistently
    sampling model parameters, realistic models of time varying phenomena (such as
    supernovae and AGNs), effect models (such as dust extinction), and survey
    characteristics (such as cadence, filters, and noise).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeremykubica
    - hombit
    - mi-dai
    - olivialynn
